num_1=float(input("Digite um número:"))
num_2=float(input("Digite um número:"))
soma=(num_1+num_2)
subtra=(num_1-num_2)
mult=(num_1*num_2)
div=(num_1/num_2)
print("A soma deu:",soma)
print("A subtração:",subtra)
print("A multiplicação:",mult)
print("A divisão:",div)
